---
- name: Install Apache
  apk:
    name: apache2
    state: present
    update_cache: yes

- name: Create Web Root
  file:
    path: /var/www/localhost/htdocs
    state: directory
    owner: praetor
    group: praetor
    mode: '0755'

- name: Deploy Index Page
  template:
    src: index.html.j2
    dest: /var/www/localhost/htdocs/index.html
    owner: praetor
    group: praetor
    mode: '0644'

- name: Ensure Apache is running
  command: httpd -k start
  register: apache_start
  failed_when: "'already running' not in apache_start.stderr and apache_start.rc != 0"
  changed_when: apache_start.rc == 0

