---
- name: Install Apache
  apk:
    name: apache2
    state: present
    update_cache: yes

- name: Create Web Root
  file:
    path: /var/www/localhost/htdocs
    state: directory
    owner: praetor
    group: praetor
    mode: '0755'

- name: Deploy Index Page
  template:
    src: index.html.j2
    dest: /var/www/localhost/htdocs/index.html
    owner: praetor
    group: praetor
    mode: '0644'

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes

